dist: bionic
sudo: false

language: python
python:
  - "3.7"

notifications:
  email: false

env:
  # Example test environments
  - TEST_PLATFORM="mega2560"
  - TEST_PLATFORM="mega1280"
  - TEST_PLATFORM="rambo"
  - TEST_PLATFORM="STM32F103VE_longer"
  - TEST_PLATFORM="mega2560ext"
  - TEST_PLATFORM="sanguino1284p"
  - TEST_PLATFORM="melzi"
  - TEST_PLATFORM="melzi_optimized"
  - TEST_PLATFORM="melzi_optiboot"
  - TEST_PLATFORM="ARMED"
  - TEST_PLATFORM="LPC1769"
  - TEST_PLATFORM="LPC1768"
  - TEST_PLATFORM="STM32F103RC_btt"
  - TEST_PLATFORM="STM32F103RC_btt_512K"
  - TEST_PLATFORM="STM32F103RC_btt_USB"
  - TEST_PLATFORM="STM32F103RC_btt_512K_USB"
  - TEST_PLATFORM="STM32F103RC_meeb"
  - TEST_PLATFORM="STM32F103RE_btt"
  - TEST_PLATFORM="STM32F103RE_btt_USB"
  - TEST_PLATFORM="STM32F103RET6_creality"
  - TEST_PLATFORM="STM32F103RC_fysetc"
  - TEST_PLATFORM="mks_robin_e3"
  - TEST_PLATFORM="trigorilla_pro"
  - TEST_PLATFORM="mks_robin_nano35"
  - TEST_PLATFORM="mks_robin_mini"
  - TEST_PLATFORM="STM32F103RE"
  - TEST_PLATFORM="at90usb1286_cdc"
  - TEST_PLATFORM="malyan_M300"
  - TEST_PLATFORM="FYSETC_S6"
  - TEST_PLATFORM="sanguino644p"
  - TEST_PLATFORM="jgaurora_a5s_a1"
  - TEST_PLATFORM="DUE"
  - TEST_PLATFORM="DUE_USB"
  - TEST_PLATFORM="DUE_debug"
  - TEST_PLATFORM="at90usb1286_dfu"
  - TEST_PLATFORM="STM32F103CB_malyan"
  - TEST_PLATFORM="mks_robin"
  - TEST_PLATFORM="mks_robin_stm32"
  - TEST_PLATFORM="mks_robin_lite3"
  - TEST_PLATFORM="mks_robin_pro"
  - TEST_PLATFORM="BIGTREE_BTT002"
  - TEST_PLATFORM="STM32F407VE_black"
  - TEST_PLATFORM="STM32F4"
  - TEST_PLATFORM="STM32F7"
  - TEST_PLATFORM="chitu_f103"
  - TEST_PLATFORM="chitu_v5_gpio_init"
  - TEST_PLATFORM="DUE_archim"
  - TEST_PLATFORM="DUE_archim_debug"


before_install:
  #
  # Fetch the tag information for the current branch
  - git fetch origin --tags
  #
  # Publish the buildroot script folder
  #- dos2unix ${TRAVIS_BUILD_DIR}/buildroot/bin/*
  - chmod +x ${TRAVIS_BUILD_DIR}/buildroot/bin/*
  #- dos2unix ${TRAVIS_BUILD_DIR}/buildroot/share/tests/*
  - chmod +x ${TRAVIS_BUILD_DIR}/buildroot/tests/run_tests
  - export PATH="${TRAVIS_BUILD_DIR}/buildroot/bin/:${TRAVIS_BUILD_DIR}/buildroot/share/tests/:${PATH}"



install:
  #- pip install -U platformio
  - pip install -U https://github.com/platformio/platformio-core/archive/master.zip

before_script:
  # Update PlatformIO packages
  - platformio update
  #
  # Change current working directory to the build dir
  - cd ${TRAVIS_BUILD_DIR}
  #
  # Generate custom version include
  - generate_version ${TRAVIS_BUILD_DIR}/Marlin/
  - cat ${TRAVIS_BUILD_DIR}/Marlin/Version.h
  #
script:
  - echo ${PATH}
  - run_tests ${TRAVIS_BUILD_DIR} ${TEST_PLATFORM}

