#!/usr/bin/env bash
#
# Build tests for ARMED
#

# exit on first failure
set -e

# Build examples
restore_configs
use_example_configs ArmEd
exec_test $1 $2 "Example: ArmEd"

# cleanup
restore_configs
