#!/usr/bin/env bash
#
# Build tests for at90usb1286_dfu
#

# exit on first failure
set -e

# Build examples
restore_configs
use_example_configs Printrbot/Simple\ Metal\ RevD
exec_test $1 $2 "Example: Printrbot/Simple\ Metal\ RevD"
restore_configs
use_example_configs makibox
exec_test $1 $2 "Example: makibox"

# cleanup
restore_configs
