#!/usr/bin/env bash
#
# Build tests for at90usb1286_cdc
#

# exit on first failure
set -e

# Build examples
restore_configs
use_example_configs delta/kossel_pro
exec_test $1 $2 "Example: delta/kossel_pro"

# cleanup
restore_configs
