#!/usr/bin/env bash
#
# Build tests for BIGTREE_BTT002
#

# exit on first failure
set -e

# Build examples
restore_configs
use_example_configs Prusa/MK3S-BigTreeTech-BTT002
exec_test $1 $2 "Example: Prusa/MK3S-BigTreeTech-BTT002"

# cleanup
restore_configs
