#!/usr/bin/env bash
#
# Build tests for chitu_f103
#

# exit on first failure
set -e

# Build examples
restore_configs
use_example_configs Tronxy/X5SA
exec_test $1 $2 "Example: Tronxy/X5SA"

# cleanup
restore_configs
