#!/usr/bin/env bash
#
# Build tests for DUE_debug
#

# exit on first failure
set -e

# Build examples
restore_configs
use_example_configs MakerParts
exec_test $1 $2 "Example: MakerParts"
restore_configs
use_example_configs UltiMachine/Archim1
exec_test $1 $2 "Example: UltiMachine/Archim1"

# cleanup
restore_configs
