#!/usr/bin/env bash
#
# Build tests for DUE_USB
#

# exit on first failure
set -e

# Build examples
restore_configs
use_example_configs MakerParts
exec_test $1 $2 "Example: MakerParts"
restore_configs
use_example_configs Printrbot/PrintrboardG2
exec_test $1 $2 "Example: Printrbot/PrintrboardG2"

# cleanup
restore_configs
