#!/usr/bin/env bash
#
# Build tests for DUE_archim
#

# exit on first failure
set -e

# Build examples
restore_configs
use_example_configs UltiMachine/Archim2
exec_test $1 $2 "Example: UltiMachine/Archim2"

# cleanup
restore_configs
