#!/usr/bin/env bash
#
# Build tests for flsun_hispeed
#

# exit on first failure
set -e

# Build examples
restore_configs
use_example_configs delta/FLSUN/QQS-Pro
exec_test $1 $2 "Example: delta/FLSUN/QQS-Pro"

# cleanup
restore_configs
