#!/usr/bin/env bash
#
# Build tests for FYSETC_S6
#

# exit on first failure
set -e

# Build examples
restore_configs
use_example_configs FYSETC/S6
exec_test $1 $2 "Example: FYSETC/S6"

# cleanup
restore_configs
