#!/usr/bin/env bash
#
# Build tests for jgaurora_a5s_a1
#

# exit on first failure
set -e

# Build examples
restore_configs
use_example_configs JGAurora/A1
exec_test $1 $2 "Example: JGAurora/A1"
restore_configs
use_example_configs JGAurora/A5S
exec_test $1 $2 "Example: JGAurora/A5S"

# cleanup
restore_configs
