#!/usr/bin/env bash
#
# Build tests for LPC1768
#

# exit on first failure
set -e

# Build examples
restore_configs
use_example_configs BIQU/B1
exec_test $1 $2 "Example: BIQU/B1"
restore_configs
use_example_configs BIQU/B1-BLTouch
exec_test $1 $2 "Example: BIQU/B1-BLTouch"
restore_configs
use_example_configs Mks/Sbase
exec_test $1 $2 "Example: Mks/Sbase"
restore_configs
use_example_configs delta/MKS/SBASE
exec_test $1 $2 "Example: delta/MKS/SBASE"

# cleanup
restore_configs
