#!/usr/bin/env bash
#
# Build tests for LPC1769
#

# exit on first failure
set -e

# Build examples
restore_configs
use_example_configs Azteeg/X5GT
exec_test $1 $2 "Example: Azteeg/X5GT"
restore_configs
use_example_configs Creality/Ender-3/BigTreeTech\ SKR\ E3\ Turbo/2-into-1\ Hotend
exec_test $1 $2 "Example: Creality/Ender-3/BigTreeTech\ SKR\ E3\ Turbo/2-into-1\ Hotend"
restore_configs
use_example_configs Creality/Ender-3/BigTreeTech\ SKR\ E3\ Turbo/Dual\ Z
exec_test $1 $2 "Example: Creality/Ender-3/BigTreeTech\ SKR\ E3\ Turbo/Dual\ Z"
restore_configs
use_example_configs Creality/Ender-3/BigTreeTech\ SKR\ E3\ Turbo/Single\ Extruder
exec_test $1 $2 "Example: Creality/Ender-3/BigTreeTech\ SKR\ E3\ Turbo/Single\ Extruder"
restore_configs
use_example_configs Creality/Ender-5/BigTreeTech\ SKR\ 1.4\ Turbo\ \(TMC2209\)
exec_test $1 $2 "Example: Creality/Ender-5/BigTreeTech\ SKR\ 1.4\ Turbo\ \(TMC2209\)"
restore_configs
use_example_configs Zonestar/P802QR2/BigTreeTech\ SKR\ 1.4\ Turbo\ \(A4988\)
exec_test $1 $2 "Example: Zonestar/P802QR2/BigTreeTech\ SKR\ 1.4\ Turbo\ \(A4988\)"

# cleanup
restore_configs
