#!/usr/bin/env bash
#
# Build tests for malyan_M300
#

# exit on first failure
set -e

# Build examples
restore_configs
use_example_configs delta/Malyan\ M300
exec_test $1 $2 "Example: delta/Malyan\ M300"

# cleanup
restore_configs
