#!/usr/bin/env bash
#
# Build tests for mega2560
#

# exit on first failure
set -e

# Build examples
restore_configs
use_example_configs 3DFabXYZ/Migbot
exec_test $1 $2 "Example: 3DFabXYZ/Migbot"
restore_configs
use_example_configs ADIMLab/Gantry\ v2
exec_test $1 $2 "Example: ADIMLab/Gantry\ v2"
restore_configs
use_example_configs AliExpress/CL-260
exec_test $1 $2 "Example: AliExpress/CL-260"
restore_configs
use_example_configs AnyCubic/Chiron
exec_test $1 $2 "Example: AnyCubic/Chiron"
restore_configs
use_example_configs AnyCubic/i3
exec_test $1 $2 "Example: AnyCubic/i3"
restore_configs
use_example_configs AnyCubic/i3\ Mega
exec_test $1 $2 "Example: AnyCubic/i3\ Mega"
restore_configs
use_example_configs Artillery/Genius
exec_test $1 $2 "Example: Artillery/Genius"
restore_configs
use_example_configs Artillery/Sidewinder\ X1
exec_test $1 $2 "Example: Artillery/Sidewinder\ X1"
restore_configs
use_example_configs Artillery/Sidewinder\ X1_0.9_degree_BMG_E3D_V6
exec_test $1 $2 "Example: Artillery/Sidewinder\ X1_0.9_degree_BMG_E3D_V6"
restore_configs
use_example_configs BIBO/TouchX/cyclops
exec_test $1 $2 "Example: BIBO/TouchX/cyclops"
restore_configs
use_example_configs BIBO/TouchX/default
exec_test $1 $2 "Example: BIBO/TouchX/default"
restore_configs
use_example_configs BQ/Hephestos
exec_test $1 $2 "Example: BQ/Hephestos"
restore_configs
use_example_configs BQ/WITBOX
exec_test $1 $2 "Example: BQ/WITBOX"
restore_configs
use_example_configs CTC/i3\ 2560\ Rev\ A/no\ probe
exec_test $1 $2 "Example: CTC/i3\ 2560\ Rev\ A/no\ probe"
restore_configs
use_example_configs Cartesio
exec_test $1 $2 "Example: Cartesio"
restore_configs
use_example_configs Copymaster3D/300
exec_test $1 $2 "Example: Copymaster3D/300"
restore_configs
use_example_configs Copymaster3D/400
exec_test $1 $2 "Example: Copymaster3D/400"
restore_configs
use_example_configs Copymaster3D/500
exec_test $1 $2 "Example: Copymaster3D/500"
restore_configs
use_example_configs Creality/CR-10S/CrealityV1
exec_test $1 $2 "Example: Creality/CR-10S/CrealityV1"
restore_configs
use_example_configs Creality/CR-10\ S4/CrealityV1
exec_test $1 $2 "Example: Creality/CR-10\ S4/CrealityV1"
restore_configs
use_example_configs Creality/CR-10\ S5/CrealityV1
exec_test $1 $2 "Example: Creality/CR-10\ S5/CrealityV1"
restore_configs
use_example_configs Creality/CR-10\ V2
exec_test $1 $2 "Example: Creality/CR-10\ V2"
restore_configs
use_example_configs Creality/CR-20
exec_test $1 $2 "Example: Creality/CR-20"
restore_configs
use_example_configs Creality/CR-20\ Pro
exec_test $1 $2 "Example: Creality/CR-20\ Pro"
restore_configs
use_example_configs Creality/CR-8
exec_test $1 $2 "Example: Creality/CR-8"
restore_configs
use_example_configs Creality/Ender-4
exec_test $1 $2 "Example: Creality/Ender-4"
restore_configs
use_example_configs Creality/Ender-5_Plus
exec_test $1 $2 "Example: Creality/Ender-5_Plus"
restore_configs
use_example_configs Dagoma/Disco\ Ultimate
exec_test $1 $2 "Example: Dagoma/Disco\ Ultimate"
restore_configs
use_example_configs Daycom/3DP-100
exec_test $1 $2 "Example: Daycom/3DP-100"
restore_configs
use_example_configs EXP3D/Imprimante\ multifonction
exec_test $1 $2 "Example: EXP3D/Imprimante\ multifonction"
restore_configs
use_example_configs FYSETC/F6_13
exec_test $1 $2 "Example: FYSETC/F6_13"
restore_configs
use_example_configs Felix/DUAL
exec_test $1 $2 "Example: Felix/DUAL"
restore_configs
use_example_configs Felix/Single
exec_test $1 $2 "Example: Felix/Single"
restore_configs
use_example_configs FlyingBear/P905H
exec_test $1 $2 "Example: FlyingBear/P905H"
restore_configs
use_example_configs FolgerTech/i3-2020
exec_test $1 $2 "Example: FolgerTech/i3-2020"
restore_configs
use_example_configs Formbot/Raptor
exec_test $1 $2 "Example: Formbot/Raptor"
restore_configs
use_example_configs Formbot/T_Rex_2+
exec_test $1 $2 "Example: Formbot/T_Rex_2+"
restore_configs
use_example_configs Formbot/T_Rex_3
exec_test $1 $2 "Example: Formbot/T_Rex_3"
restore_configs
use_example_configs Geeetech/A10
exec_test $1 $2 "Example: Geeetech/A10"
restore_configs
use_example_configs Geeetech/A10D
exec_test $1 $2 "Example: Geeetech/A10D"
restore_configs
use_example_configs Geeetech/A10M
exec_test $1 $2 "Example: Geeetech/A10M"
restore_configs
use_example_configs Geeetech/A10T
exec_test $1 $2 "Example: Geeetech/A10T"
restore_configs
use_example_configs Geeetech/A20
exec_test $1 $2 "Example: Geeetech/A20"
restore_configs
use_example_configs Geeetech/A20M
exec_test $1 $2 "Example: Geeetech/A20M"
restore_configs
use_example_configs Geeetech/A20T
exec_test $1 $2 "Example: Geeetech/A20T"
restore_configs
use_example_configs Geeetech/Duplicator5
exec_test $1 $2 "Example: Geeetech/Duplicator5"
restore_configs
use_example_configs Geeetech/GT2560
exec_test $1 $2 "Example: Geeetech/GT2560"
restore_configs
use_example_configs Geeetech/I3_Pro_X-GT2560
exec_test $1 $2 "Example: Geeetech/I3_Pro_X-GT2560"
restore_configs
use_example_configs Geeetech/MeCreator2
exec_test $1 $2 "Example: Geeetech/MeCreator2"
restore_configs
use_example_configs Geeetech/Me_creator
exec_test $1 $2 "Example: Geeetech/Me_creator"
restore_configs
use_example_configs Geeetech/PI3A\ PRO
exec_test $1 $2 "Example: Geeetech/PI3A\ PRO"
restore_configs
use_example_configs Geeetech/Prusa\ i3\ Pro\ B/bltouch
exec_test $1 $2 "Example: Geeetech/Prusa\ i3\ Pro\ B/bltouch"
restore_configs
use_example_configs Geeetech/Prusa\ i3\ Pro\ B/noprobe
exec_test $1 $2 "Example: Geeetech/Prusa\ i3\ Pro\ B/noprobe"
restore_configs
use_example_configs Geeetech/Prusa\ i3\ Pro\ C
exec_test $1 $2 "Example: Geeetech/Prusa\ i3\ Pro\ C"
restore_configs
use_example_configs Geeetech/Prusa\ i3\ Pro\ W
exec_test $1 $2 "Example: Geeetech/Prusa\ i3\ Pro\ W"
restore_configs
use_example_configs HMS434
exec_test $1 $2 "Example: HMS434"
restore_configs
use_example_configs Infitary/i3-M508
exec_test $1 $2 "Example: Infitary/i3-M508"
restore_configs
use_example_configs Intamsys/FunmatHT_4988
exec_test $1 $2 "Example: Intamsys/FunmatHT_4988"
restore_configs
use_example_configs JGAurora/A3
exec_test $1 $2 "Example: JGAurora/A3"
restore_configs
use_example_configs JGAurora/A5
exec_test $1 $2 "Example: JGAurora/A5"
restore_configs
use_example_configs JGAurora/Magic
exec_test $1 $2 "Example: JGAurora/Magic"
restore_configs
use_example_configs MakerFarm/Pegasus_12
exec_test $1 $2 "Example: MakerFarm/Pegasus_12"
restore_configs
use_example_configs Micromake/C1/basic
exec_test $1 $2 "Example: Micromake/C1/basic"
restore_configs
use_example_configs Micromake/C1/enhanced
exec_test $1 $2 "Example: Micromake/C1/enhanced"
restore_configs
use_example_configs Modix/Big60
exec_test $1 $2 "Example: Modix/Big60"
restore_configs
use_example_configs Ortur\ 4
exec_test $1 $2 "Example: Ortur\ 4"
restore_configs
use_example_configs RapideLite/RL200
exec_test $1 $2 "Example: RapideLite/RL200"
restore_configs
use_example_configs Renkforce/RF100
exec_test $1 $2 "Example: Renkforce/RF100"
restore_configs
use_example_configs Renkforce/RF100XL
exec_test $1 $2 "Example: Renkforce/RF100XL"
restore_configs
use_example_configs Renkforce/RF100v2
exec_test $1 $2 "Example: Renkforce/RF100v2"
restore_configs
use_example_configs RepRapWorld/Megatronics
exec_test $1 $2 "Example: RepRapWorld/Megatronics"

### Broken due to missing entrypoint
# restore_configs
# use_example_configs RigidBot
# exec_test $1 $2 "Example: RigidBot"


restore_configs
use_example_configs Robo3D/R1+
exec_test $1 $2 "Example: Robo3D/R1+"
restore_configs
use_example_configs SCARA/MP_SCARA
exec_test $1 $2 "Example: SCARA/MP_SCARA"
restore_configs
use_example_configs SCARA/Morgan
exec_test $1 $2 "Example: SCARA/Morgan"
restore_configs
use_example_configs Sovol/SV-01
exec_test $1 $2 "Example: Sovol/SV-01"
restore_configs
use_example_configs Tevo/Michelangelo
exec_test $1 $2 "Example: Tevo/Michelangelo"
restore_configs
use_example_configs Tevo/Tarantula\ Pro
exec_test $1 $2 "Example: Tevo/Tarantula\ Pro"
restore_configs
use_example_configs Tevo/Tornado/V1\ \(MKS\ Base\)
exec_test $1 $2 "Example: Tevo/Tornado/V1\ \(MKS\ Base\)"
restore_configs
use_example_configs Tevo/Tornado/V2\ \(MKS\ GEN-L\)
exec_test $1 $2 "Example: Tevo/Tornado/V2\ \(MKS\ GEN-L\)"
restore_configs
use_example_configs Tronxy/X5S-2E
exec_test $1 $2 "Example: Tronxy/X5S-2E"
restore_configs
use_example_configs VORONDesign
exec_test $1 $2 "Example: VORONDesign"
restore_configs
use_example_configs Velleman/K8200
exec_test $1 $2 "Example: Velleman/K8200"
restore_configs
use_example_configs Velleman/K8400/Dual-head
exec_test $1 $2 "Example: Velleman/K8400/Dual-head"
restore_configs
use_example_configs Velleman/K8400/Single-head
exec_test $1 $2 "Example: Velleman/K8400/Single-head"
restore_configs
use_example_configs WASP/PowerWASP
exec_test $1 $2 "Example: WASP/PowerWASP"
restore_configs
use_example_configs Wanhao/Duplicator\ i3\ Mini
exec_test $1 $2 "Example: Wanhao/Duplicator\ i3\ Mini"
restore_configs
use_example_configs adafruit/ST7565
exec_test $1 $2 "Example: adafruit/ST7565"
restore_configs
use_example_configs delta/Anycubic/Kossel
exec_test $1 $2 "Example: delta/Anycubic/Kossel"
restore_configs
use_example_configs delta/Anycubic/Kossel\ Linear\ Plus
exec_test $1 $2 "Example: delta/Anycubic/Kossel\ Linear\ Plus"
restore_configs
use_example_configs delta/Dreammaker/Overlord
exec_test $1 $2 "Example: delta/Dreammaker/Overlord"

### Intentionally fails due to power supply requirement
# restore_configs
# use_example_configs delta/Dreammaker/Overlord_Pro
# exec_test $1 $2 "Example: delta/Dreammaker/Overlord_Pro"

restore_configs
use_example_configs delta/FLSUN/auto_calibrate
exec_test $1 $2 "Example: delta/FLSUN/auto_calibrate"
restore_configs
use_example_configs delta/FLSUN/kossel
exec_test $1 $2 "Example: delta/FLSUN/kossel"
restore_configs
use_example_configs delta/FLSUN/kossel_mini
exec_test $1 $2 "Example: delta/FLSUN/kossel_mini"
restore_configs
use_example_configs delta/Geeetech/G2
exec_test $1 $2 "Example: delta/Geeetech/G2"
restore_configs
use_example_configs delta/Geeetech/G2Pro
exec_test $1 $2 "Example: delta/Geeetech/G2Pro"
restore_configs
use_example_configs delta/Geeetech/G2S
exec_test $1 $2 "Example: delta/Geeetech/G2S"
restore_configs
use_example_configs delta/Geeetech/G2SPro
exec_test $1 $2 "Example: delta/Geeetech/G2SPro"
restore_configs
use_example_configs delta/Hatchbox_Alpha
exec_test $1 $2 "Example: delta/Hatchbox_Alpha"
restore_configs
use_example_configs delta/Tevo\ Little\ Monster
exec_test $1 $2 "Example: delta/Tevo\ Little\ Monster"
restore_configs
use_example_configs delta/generic
exec_test $1 $2 "Example: delta/generic"
restore_configs
use_example_configs delta/kossel_clear
exec_test $1 $2 "Example: delta/kossel_clear"
restore_configs
use_example_configs delta/kossel_mini
exec_test $1 $2 "Example: delta/kossel_mini"
restore_configs
use_example_configs delta/kossel_xl
exec_test $1 $2 "Example: delta/kossel_xl"

### BLTouch problems
# restore_configs
# use_example_configs gCreate/gMax1.5+
# exec_test $1 $2 "Example: gCreate/gMax1.5+"

# cleanup
restore_configs
