#!/usr/bin/env bash
#
# Build tests for melzi_optiboot
#

# exit on first failure
set -e

# Build examples
restore_configs
use_example_configs AnyCubic/Mega\ Zero/Anycubic\ V1
exec_test $1 $2 "Example: AnyCubic/Mega\ Zero/Anycubic\ V1"
restore_configs
use_example_configs Creality/CR-10/CrealityV1
exec_test $1 $2 "Example: Creality/CR-10/CrealityV1"
restore_configs
use_example_configs Creality/CR-10\ Mini/CrealityV1
exec_test $1 $2 "Example: Creality/CR-10\ Mini/CrealityV1"
restore_configs
use_example_configs Creality/Ender-2
exec_test $1 $2 "Example: Creality/Ender-2"
restore_configs
use_example_configs Creality/Ender-3/CrealityV1
exec_test $1 $2 "Example: Creality/Ender-3/CrealityV1"
restore_configs
use_example_configs Creality/Ender-3\ Pro/CrealityV1
exec_test $1 $2 "Example: Creality/Ender-3\ Pro/CrealityV1"
restore_configs
use_example_configs Creality/Ender-5/CrealityV1
exec_test $1 $2 "Example: Creality/Ender-5/CrealityV1"
restore_configs
use_example_configs Creality/Ender-5\ Pro/CrealityV1
exec_test $1 $2 "Example: Creality/Ender-5\ Pro/CrealityV1"

# cleanup
restore_configs
