#!/usr/bin/env bash
#
# Build tests for mks_robin_mini
#

# exit on first failure
set -e

# Build examples
restore_configs
use_example_configs Kingroon/KP3
exec_test $1 $2 "Example: Kingroon/KP3"
restore_configs
use_example_configs delta/FLSUN/QQ-S
exec_test $1 $2 "Example: delta/FLSUN/QQ-S"

# cleanup
restore_configs
