#!/usr/bin/env bash
#
# Build tests for mks_robin_pro
#

# exit on first failure
set -e

# Build examples
restore_configs
use_example_configs Mks/Robin_Pro
exec_test $1 $2 "Example: Mks/Robin_Pro"

# cleanup
restore_configs
