#!/usr/bin/env bash
#
# Build tests for mks_robin_nano35
#

# exit on first failure
set -e

# Build examples
restore_configs
use_example_configs Tevo/Nereus
exec_test $1 $2 "Example: Tevo/Nereus"
restore_configs
use_example_configs delta/FLSUN/Q5-nano_v1
exec_test $1 $2 "Example: delta/FLSUN/Q5-nano_v1"
restore_configs
use_example_configs delta/FLSUN/Q5-nano_v2
exec_test $1 $2 "Example: delta/FLSUN/Q5-nano_v2"

# cleanup
restore_configs
