#!/usr/bin/env bash
#
# Build tests for mks_robin
#

# exit on first failure
set -e

# Build examples
restore_configs
use_example_configs Mks/Robin
exec_test $1 $2 "Example: Mks/Robin"

# cleanup
restore_configs
