#!/usr/bin/env bash
#
# Build tests for mks_robin_nano35
#

# exit on first failure
set -e

# Build examples
restore_configs
use_example_configs Tevo/Nereus
exec_test $1 $2 "Example: Tevo/Nereus"
restore_configs
use_example_configs delta/FLSUN/Q5-nano_v1
exec_test $1 $2 "Example: delta/FLSUN/Q5-nano_v1"
restore_configs
use_example_configs delta/FLSUN/Q5-nano_v2
exec_test $1 $2 "Example: delta/FLSUN/Q5-nano_v2"

#
# MKS Robin v2 nano LVGL SPI + TMC
# (Robin v2 nano has no FSMC interface)
#
use_example_configs Mks/Robin
opt_set MOTHERBOARD BOARD_MKS_ROBIN_NANO_V2
opt_disable TFT_INTERFACE_FSMC TFT_COLOR_UI TOUCH_SCREEN TFT_RES_320x240
opt_enable TFT_INTERFACE_SPI TFT_LVGL_UI TFT_RES_480x320
opt_set X_DRIVER_TYPE TMC2209
opt_set Y_DRIVER_TYPE TMC2209
exec_test $1 $2 "MKS Robin v2 nano LVGL SPI + TMC"

# cleanup
restore_configs
