#!/usr/bin/env bash
#
# Build tests for mks_robin_lite3
#

# exit on first failure
set -e

# Build examples
restore_configs
use_example_configs Mks/Robin_Lite3
exec_test $1 $2 "Example: Mks/Robin_Lite3"

# cleanup
restore_configs
