#!/usr/bin/env bash
#
# Build tests for rambo
#

# exit on first failure
set -e

# Build examples
restore_configs
use_example_configs AlephObjects/TAZ4
exec_test $1 $2 "Example: AlephObjects/TAZ4"

# cleanup
restore_configs
