#!/usr/bin/env bash
#
# Build tests for sanguino644p
#

# exit on first failure
set -e

# Build examples
restore_configs
use_example_configs Geeetech/Me_ducer
exec_test $1 $2 "Example: Geeetech/Me_ducer"
restore_configs
use_example_configs Malyan/M150
exec_test $1 $2 "Example: Malyan/M150"
restore_configs
use_example_configs RepRapPro/Huxley
exec_test $1 $2 "Example: RepRapPro/Huxley"
restore_configs
use_example_configs Sanguinololu
exec_test $1 $2 "Example: Sanguinololu"
restore_configs
use_example_configs TinyBoy2
exec_test $1 $2 "Example: TinyBoy2"
restore_configs
use_example_configs Tronxy/X1
exec_test $1 $2 "Example: Tronxy/X1"
restore_configs
use_example_configs Tronxy/X3A
exec_test $1 $2 "Example: Tronxy/X3A"
restore_configs
use_example_configs Tronxy/X5S
exec_test $1 $2 "Example: Tronxy/X5S"
restore_configs
use_example_configs Tronxy/XY100
exec_test $1 $2 "Example: Tronxy/XY100"
restore_configs
use_example_configs Wanhao/Duplicator\ i3\ 2.1
exec_test $1 $2 "Example: Wanhao/Duplicator\ i3\ 2.1"
restore_configs
use_example_configs Zonestar/P802M
exec_test $1 $2 "Example: Zonestar/P802M"
restore_configs
use_example_configs tvrrug/Round2
exec_test $1 $2 "Example: tvrrug/Round2"

# cleanup
restore_configs
