#!/usr/bin/env bash
#
# Build tests for STM32F407VE_black
#

# exit on first failure
set -e

# Build examples
restore_configs
use_example_configs STM32/Black_STM32F407VET6
exec_test $1 $2 "Example: STM32/Black_STM32F407VET6"

# cleanup
restore_configs
