#!/usr/bin/env bash
#
# Build tests for STM32F103RE
#

# exit on first failure
set -e

# Build examples
restore_configs
use_example_configs Geeetech/A30
exec_test $1 $2 "Example: Geeetech/A30"
restore_configs
use_example_configs Geeetech/D200
exec_test $1 $2 "Example: Geeetech/D200"
restore_configs
use_example_configs Geeetech/E180
exec_test $1 $2 "Example: Geeetech/E180"
restore_configs
use_example_configs Geeetech/M201
exec_test $1 $2 "Example: Geeetech/M201"
restore_configs
use_example_configs STM32/STM32F103RE
exec_test $1 $2 "Example: STM32/STM32F103RE"
restore_configs
use_example_configs delta/Geeetech/Rostock\ 301
exec_test $1 $2 "Example: delta/Geeetech/Rostock\ 301"

# cleanup
restore_configs
