#!/usr/bin/env bash
#
# Build tests for STM32F103RC_btt_512K
#

# exit on first failure
set -e

# Build examples
restore_configs
use_example_configs AnyCubic/Mega\ Zero/BigTreeTech\ SKR\ Mini\ MZ\ V1.0
exec_test $1 $2 "Example: AnyCubic/Mega\ Zero/BigTreeTech\ SKR\ Mini\ MZ\ V1.0"
restore_configs
use_example_configs Creality/CR-10/BigTreeTech\ SKR\ Mini\ E3\ 2.0
exec_test $1 $2 "Example: Creality/CR-10/BigTreeTech\ SKR\ Mini\ E3\ 2.0"
restore_configs
use_example_configs Creality/CR-10S/BigTreeTech\ SKR\ Mini\ E3\ 2.0
exec_test $1 $2 "Example: Creality/CR-10S/BigTreeTech\ SKR\ Mini\ E3\ 2.0"
restore_configs
use_example_configs Creality/Ender-3/BigTreeTech\ SKR\ E3-DIP\ V1.1
exec_test $1 $2 "Example: Creality/Ender-3/BigTreeTech\ SKR\ E3-DIP\ V1.1"
restore_configs
use_example_configs Creality/Ender-3/BigTreeTech\ SKR\ Mini\ E3\ 1.0
exec_test $1 $2 "Example: Creality/Ender-3/BigTreeTech\ SKR\ Mini\ E3\ 1.0"
restore_configs
use_example_configs Creality/Ender-3/BigTreeTech\ SKR\ Mini\ E3\ 1.2
exec_test $1 $2 "Example: Creality/Ender-3/BigTreeTech\ SKR\ Mini\ E3\ 1.2"
restore_configs
use_example_configs Creality/Ender-3/BigTreeTech\ SKR\ Mini\ E3\ 2.0
exec_test $1 $2 "Example: Creality/Ender-3/BigTreeTech\ SKR\ Mini\ E3\ 2.0"
restore_configs
use_example_configs Creality/Ender-3\ Pro/BigTreeTech\ SKR\ Mini\ E3\ 1.0
exec_test $1 $2 "Example: Creality/Ender-3\ Pro/BigTreeTech\ SKR\ Mini\ E3\ 1.0"
restore_configs
use_example_configs Creality/Ender-3\ Pro/BigTreeTech\ SKR\ Mini\ E3\ 1.2
exec_test $1 $2 "Example: Creality/Ender-3\ Pro/BigTreeTech\ SKR\ Mini\ E3\ 1.2"
restore_configs
use_example_configs Creality/Ender-3\ Pro/BigTreeTech\ SKR\ Mini\ E3\ 2.0
exec_test $1 $2 "Example: Creality/Ender-3\ Pro/BigTreeTech\ SKR\ Mini\ E3\ 2.0"
restore_configs
use_example_configs Creality/Ender-5/BigTreeTech\ SKR\ Mini\ E3\ 2.0
exec_test $1 $2 "Example: Creality/Ender-5/BigTreeTech\ SKR\ Mini\ E3\ 2.0"

# cleanup
restore_configs
