#!/usr/bin/env bash
#
# Build tests for STM32F103RC_meeb
#

# exit on first failure
set -e

# Build examples
restore_configs
use_example_configs Creality/CR-10\ Mini/MEEB-3DP
exec_test $1 $2 "Example: Creality/CR-10\ Mini/MEEB-3DP"
restore_configs
use_example_configs Creality/Ender-3/MEEB-3DP
exec_test $1 $2 "Example: Creality/Ender-3/MEEB-3DP"

# cleanup
restore_configs
