#!/usr/bin/env bash
#
# Build tests for STM32F4
#

# exit on first failure
set -e

# Build examples
restore_configs
use_example_configs STM32/STM32F4
exec_test $1 $2 "Example: STM32/STM32F4"

# cleanup
restore_configs
