#!/usr/bin/env bash
#
# Build tests for STM32F103RE_btt_USB
#

# exit on first failure
set -e

# Build examples
restore_configs
use_example_configs Creality/Ender-3/BigTreeTech\ SKR\ E3-DIP\ V1.1
exec_test $1 $2 "Example: Creality/Ender-3/BigTreeTech\ SKR\ E3-DIP\ V1.1"

# cleanup
restore_configs
