#!/usr/bin/env bash
#
# Build tests for STM32F103VE_longer
#

# exit on first failure
set -e

# Build examples
restore_configs
use_example_configs Alfawise/U20
exec_test $1 $2 "Example: Alfawise/U20"
restore_configs
use_example_configs Alfawise/U20-bltouch
exec_test $1 $2 "Example: Alfawise/U20-bltouch"

# cleanup
restore_configs
