#!/usr/bin/env bash
#
# Build tests for STM32F7
#

# exit on first failure
set -e

# Build examples
restore_configs
use_example_configs TheBorg
exec_test $1 $2 "Example: TheBorg"

# cleanup
restore_configs
