#!/usr/bin/env bash
#
# Build tests for trigorilla_pro
#

# exit on first failure
set -e

# Build examples
restore_configs
use_example_configs delta/Anycubic/Predator
exec_test $1 $2 "Example: delta/Anycubic/Predator"

# cleanup
restore_configs
